spring:
  application:
    name: organice-dia
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/organice}
    username: ${DATABASE_USERNAME:organice}
    password: ${DATABASE_PASSWORD:organice123321}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: dia
  jpa:
    properties:
      hibernate:
        default_schema: dia

springdoc:
  api-docs:
    path: /dia/v3/api-docs
  swagger-ui:
    path: /dia/swagger-ui.html


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}